name: 'shelf_redis_session_store'
version: 0.0.2
description: A web server built using the shelf package.
author: takyam <takayuki.yamaguch.m@gmail.com>
homepage: https://github.com/takyam-git/shelf_redis_session_store
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  shelf: ^0.6.1+1
  redis: ^0.4.3
  crypt: ^0.0.1
dev_dependencies:
  test: ">=0.12.0 <0.13.0"
  mockito: ">=0.8.2 <0.9.0"
transformers:
- test/pub_serve:
    $include: test/**_test.dart